name: build web
on: 
  push:
    branches:
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  build-local:
    runs-on: linux
    env:
      registry: git.yumo.pub/docker/rust-go
      image: sse-queue:dev
    steps:
      - name: checkout
        uses: https://git.yumo.pub/github/checkout@v3
        retry: 3
      - name: build executable
        run: cargo build --release
      - name: build image
        run: |
          mkdir -p docker-build
          mv target/release/sse-queue docker-build/sse-queue
          cd docker-build
          docker build -t ${registry}/${image} .
          docker login ${registry} -u ${{ secrets.docker_user }} -p ${{ secrets.docker_passwd }}
          docker push ${registry}/${image}          
        retry: 2    

  deploy-on-nas:
    runs-on: linux
    needs: [build-local]
    steps:
      - name: deploy
        uses: https://git.yumo.pub/github/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: nas.lan
          user: yumo
          key: ${{ secrets.ssh_key }}
          first_ssh: |
            cd /volume2/docker/r2-work
            /usr/local/bin/docker-compose pull
            /usr/local/bin/docker-compose up -d --build 